### ISSUE TITLE
Some titles are problems

### ISSUE THREAD

**Issue by jimlynnjulian** [patrickenfuego/matroska-tag-generator#2]
I've tried the software and found some titles are problematic. I don't know why, but several tagging search functions have a problem with "the Matrix (1999)." Yours does too.

PS C:\Temp\__video mkv\MKV and tags\__Pfuego mkv tagger TMDB> .\MatroskaTagGenerator.ps1 -Path 'The Matrix (1999).mkv' -APIKey '12345678901234567890' -Title 'The Matrix' -Year 1999 -Properties overview, title, release_date
 __  __   _  __ __   __    _____                    ___                                   _
|  \/  | | |/ / \ \ / /   |_   _|  __ _   __ _     / __|  ___   _ _    ___   _ _   __ _  | |_   ___   _ _
| |\/| | | ' <   \ V /      | |   / _` | / _` |   | (_ | / -_) | ' \  / -_) | '_| / _` | |  _| / _ \ | '_|
|_|  |_| |_|\_\   \_/       |_|   \__,_| \__, |    \___| \___| |_||_| \___| |_|   \__,_|  \__| \___/ |_|
                                         |___/

Requesting TMDB ID for 'The Matrix'...
ID successfully retrieved! ID: 603 684428 684431
---------------------------------------------
Requesting TMDB ID for 'Ex Machina'...
C:\Temp\__video mkv\MKV and tags\__Pfuego mkv tagger TMDB\MatroskaTagGenerator.ps1 : Failed to generate XML file.
Exception: Cannot validate argument on parameter 'Metadata'. The argument is null or empty. Provide an argument that
is not null or empty, and then try the command again.
At line:1 char:1
+ .\MatroskaTagGenerator.ps1 -Path 'The Matrix (1999).mkv' -APIKey '4d6 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,MatroskaTagGenerator.ps1

**Comment by patrickenfuego** [comment]
@jimlynnjulian Yes, I noticed this a while back and forgot to update this repo. This issue is caused by the same film with multiple release year titles or title revisions (remastered, etc.) which causes the API to return multiple results.

In the meantime, I have addressed this problem in another one of my repos that uses this script as a dependency, which you can find [here](https://github.com/patrickenfuego/FFEncoder). It is inside the `scripts` directory. Since the update, I haven't seen any issues in ~150 pulls, although I don't doubt some films may still present issues. Give it a try and let me know if it fixes your issue with the Matrix specifically.

I will take the changes I made to my other repo and migrate them to this repo shortly, thank you for reminding me.

**Comment by jimlynnjulian** [comment]
Ran the script with "The Matrix" as title and got a single, correct entry back.
Thanks for the update.
